### ISSUE TITLE
windows 10 提示 vcruntimed140.dll

### ISSUE THREAD

**Issue by andfk44** [MuggleWei/yoauth#1]
windows 10 提示 vcruntimed140.dll 错误

**Comment by MuggleWei** [comment]
哦，十分抱歉，在上传 **v1.0.16** 版本 windows 发部包时，误将其中一个依赖库的 debug 版本打进去了，导致了提示找不到  vcruntimed140.dll 的错误，刚刚已经重新上传 windows 版本的发布包了！
谢谢提醒！ 😀
